apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  role: KarpenterNodeRole-karpenter-eks-cluster
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: karpenter-eks-cluster
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: karpenter-eks-cluster
  amiFamily: Bottlerocket
  amiSelectorTerms:
  - id: ami-0bcf5a18999f1f877
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
spec:
  template:
    metadata:
      labels:
        fastapi.piercuta.com/node-type: karpenter
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      requirements:
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values: [c, m, r]
      - key: karpenter.k8s.aws/instance-generation
        operator: Gt
        values: ["2"]
      - key: karpenter.sh/capacity-type
        operator: In
        values: ["on-demand"]
